apiVersion: apps/v1
kind: Deployment
metadata:
    name: celery-worker
    labels:
        deployment: celery-worker
spec:
    replicas: 1
    selector:
        matchLabels:
            pod: celery-worker
    template:
        metadata:
            labels:
                pod: celery-worker
        spec:
            containers:
                - name: celery-worker
                  image: aitoyregistry.azurecr.io/aitoy:latest
                  command:
                      [
                          "poetry",
                          "run",
                          "celery",
                          "-A",
                          "app.celery.worker.celery_app",
                          "worker",
                          "-l",
                          "info",
                      ]
                  envFrom:
                      - secretRef:
                            name: fastapi-prod-env

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: celery-worker
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: celery-worker
    minReplicas: 1
    maxReplicas: 30
    targetCPUUtilizationPercentage: 90